const FETCH_STARWARS_REQUEST = 'FETCH_STARWARS_REQUEST';
const FETCH_STARWARS_SUCCESS = 'FETCH_STARWARS_SUCCESS';
const FETCH_STARWARS_FAILURE = 'FETCH_STARWARS_FAILURE';

export {
  FETCH_STARWARS_REQUEST,
  FETCH_STARWARS_SUCCESS,
  FETCH_STARWARS_FAILURE,
};
